<script type="text/javascript" src="{{ asset('assets/aperi/assets/plugins/jquery/jquery-1.12.3.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/assets/plugins/tether/js/tether.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/assets/plugins/bootstrap4/js/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/assets/plugins/detectmobilebrowser/detectmobilebrowser.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/assets/plugins/jscrollpane/jquery.mousewheel.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/assets/plugins/jscrollpane/mwheelIntent.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/assets/plugins/toastr/toastr.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/js/icheck.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mobile-detect/1.4.4/mobile-detect.min.js"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/assets/plugins/jquery-fullscreen-plugin/jquery.fullscreen-min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/js/jquery-confirm.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/js/angular.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/js/lang_change.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/js/vcxLayout.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/js/sweetalert.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/enableX/js/EnxRtc.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/js/EnxWb.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/js/moment.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/enableX/js/util.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/js/vcx_settings.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/js/error.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/js/joinedRoom.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/js/RoomLayout.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/js/settings.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/js/app.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/js/scrollbar.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/aperi/js/pm.js') }}"></script>
